base_url = "https://mambucodev.github.io"
title = "Mambuco"
theme = "duckquill"

compile_sass = true
build_search_index = true

[markdown]
highlight_code = false

[extra]
accent_color = "#7b98e0"
show_read_time = true
show_share_button = true

[extra.nav]
show_feed = true
links = [
    { url = "@/blog/_index.md", name = "Blog" },
    { url = "@/projects.md", name = "Projects" },
    { url = "@/contacts.md", name = "Contacts" },
]