name: Send to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push to github
    runs-on: docker
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Updates Source
        run: git pull https://source.thundernetwork.org/ThunderNetworkRaD/blog
      - name: Set remote
        run: git remote set-url origin https://KillerBossOriginal:${{ secrets.PUSH_SECRET }}@github.com/ThunderNetworkRaD/blog.git
      - name: Updates End
        run: git pull
      - name: Push
        run: git push --force-with-lease
