name: Send to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push to github
    runs-on: docker
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Set remote
        run: git remote set-url origin https://$PUSH_SECRET@github.com/ThunderNetworkRaD/blog.git
      - name: Push
        run: git push https://github.com/ThunderNetworkRaD/blog
